# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:21
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0003_auto_20170525_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='fotos')),
            ],
            options={
                'verbose_name': 'Foto de reporte',
                'verbose_name_plural': 'Fotos de reportes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(choices=[(False, 'Abierto'), (True, 'Cerrado')], default=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('resend', models.BooleanField(default=False, verbose_name='Re enviar al cliente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Cliente')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reporte', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_reporte', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tipo_re', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tipo_re', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de reporte',
                'verbose_name_plural': 'Tipos de reportes',
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_de_reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.TipoReporte'),
        ),
        migrations.AddField(
            model_name='fotoreporte',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.Reporte'),
        ),
    ]
