# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novedades', '0003_auto_20170530_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='tipo_de_reporte',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_reporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiporeporte',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiporeporte',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_tipo_re', to=settings.AUTH_USER_MODEL),
        ),
    ]
