# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0006_auto_20170606_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoreporte',
            name='url',
        ),
    ]
