# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_remove_fotoreporte_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='numero',
        ),
    ]
