# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170530_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
