# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20170601_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
