# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20170605_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
