# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('operacion', '0008_remove_tarea_empleados'),
        ('novedades', '0007_remove_fotoreporte_url'),
        ('usuarios', '0011_auto_20170613_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_editor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='empleados',
        ),
        migrations.DeleteModel(
            name='Asistente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
