# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direcci\xf3n')),
                ('telfono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono')),
            ],
        ),
        migrations.CreateModel(
            name='Completado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('terminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompletadoSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, max_length=400, null=True, verbose_name='Direcci\xf3n')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=b'')),
                ('audio', models.BooleanField()),
                ('foto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripci\xf3n')),
                ('fecha_de_ejecucion', models.DateField()),
                ('repetir_cada', models.TextField(default=0)),
                ('sub_complete', models.BooleanField()),
                ('unidad_de_repeticion', models.IntegerField(blank=True, choices=[(3, 'Mes(es)'), (4, 'A\xf1o(s)')], default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
