# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(to='usuarios.Empleado'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='grupos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Grupo'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Tarea'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='completado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Completado'),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='subtarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.SubTarea'),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completado',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Tarea'),
        ),
        migrations.AddField(
            model_name='completado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Tipo', verbose_name='Tipo de identifiaci\xf3n'),
        ),
    ]
