# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:21
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0002_auto_20170524_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Mi cliente', 'verbose_name_plural': 'Mis clientes'},
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='grupos',
            new_name='grupo',
        ),
        migrations.RemoveField(
            model_name='completado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='completadosub',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completado',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_completado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completado',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_completado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_completadosub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_completadosub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lugar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_lugar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_subtarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_subtarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Cliente'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Lugar'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tipo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipo',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
