# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_auto_20170603_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telfono',
            new_name='telefono',
        ),
    ]
