# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_auto_20170605_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='repetir_cada',
            field=models.TextField(default=0, verbose_name='Repetir'),
        ),
    ]
