# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_auto_20170606_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='empleados',
        ),
    ]
