# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20170614_0255'),
        ('operacion', '0008_remove_tarea_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(to='usuarios.Empleado'),
        ),
    ]
