# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0009_tarea_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completado',
            name='terminado',
            field=models.BooleanField(default=True),
        ),
    ]
