# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('operacion', '0011_auto_20170824_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='repetir_cada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='unidad_de_repeticion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='crontab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djcelery.CrontabSchedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djcelery.IntervalSchedule'),
            preserve_default=False,
        ),
    ]
