# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_auto_20170906_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_de_ejecucion',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='crontab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.CrontabSchedule'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.IntervalSchedule'),
        ),
    ]
