# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('operacion', '0013_auto_20170906_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabDateSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djcelery.CrontabSchedule')),
                ('start_date', models.DateTimeField()),
            ],
            bases=('djcelery.crontabschedule',),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_ejecucion',
            field=models.DateTimeField(default='1910-04-10'),
            preserve_default=False,
        ),
    ]
