# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_auto_20170907_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='crontab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.CrontabDateSchedule'),
        ),
    ]
