# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_auto_20170907_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
