# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('operacion', '0021_auto_20170914_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontabdateschedule',
            name='crontabschedule_ptr',
        ),
        migrations.DeleteModel(
            name='CrontabDateSchedule',
        ),
    ]
