# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0023_auto_20170914_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='cron_ejecucion',
            field=models.OneToOneField(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask'),
            preserve_default=False,
        ),
    ]
