# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0026_auto_20170914_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='SubNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripci\xf3n')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Notificacion')),
                ('subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.SubTarea')),
            ],
        ),
        migrations.AlterField(
            model_name='completado',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operacion.Notificacion'),
        ),
    ]
