# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0029_auto_20170914_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completado',
            old_name='tarea',
            new_name='notificacion',
        ),
    ]
