# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0030_auto_20170914_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completado',
            name='terminado',
        ),
    ]
