# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0031_remove_completado_terminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completadosub',
            old_name='subtarea',
            new_name='subnotificacion',
        ),
    ]
