# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacion', '0032_auto_20170914_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='completado',
            name='descompletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completado',
            name='descompletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descompletado_por_completado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completado',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completado',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completadosub',
            name='descompletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='descompletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descompletado_por_completado_sub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completadosub',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completadosub',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subnotificacion',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subnotificacion',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtarea',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtarea',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
