# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0033_auto_20170915_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='descripcion',
            field=models.TextField(default='d', max_length=400, verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='latitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='longitud',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nombre',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
