# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0034_auto_20170915_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completado',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Notificacion'),
        ),
        migrations.AlterField(
            model_name='completadosub',
            name='subnotificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.SubNotificacion'),
        ),
    ]
