# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0035_auto_20170915_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='tarea',
            new_name='notificacion',
        ),
    ]
