version: "2"
services:
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27018
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/exile
    ports:
      - "8000:8081"
    links:
      - mongodb
      - redis
  celery_worker:
    build: .
    command: python manage.py celery -A exile worker -l info
    volumes:
      - .:/exile
    depends_on:
      - web
    links:
      - redis
  celery_beat:
    build: .
    command: python manage.py celery -A exile beat -l info
    volumes:
      - .:/exile
    depends_on:
      - web
    links:
      - redis
