version: "2"
services:
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 exile.asgi:channel_layer
    volumes:
      - .:/exile
    ports:
      - "8000:8000"
    links:
      - redis
      - mongodb
    depends_on:
      - worker
  worker:
    build: .
    volumes:
      - .:/exile
    command: python manage.py runworker --only-channels=http.* --only-channels=websocket
    depends_on:
      - redis
    links:
      - redis
