version: "2"
services:
  redis:
    image: "redis:latest"
    ports:
      - 6379:6380
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27020
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/exile
    ports:
      - "8000:8000"
    links:
      - redis
      - mongodb
